

const MAX_TEMPLATE_ALLOWED = 50;
const MAX_QUIZ_ALLOWED = 50;
const MAX_MEMBERS_ALLOWED = 25;
const MAX_RESPONSES_ALLOWED = 500;
const MAX_Q_PER_SURVEY = 20;
const MAX_OPT_PER_Q = 200;





module.exports = {
    MAX_TEMPLATE_ALLOWED,    
    MAX_QUIZ_ALLOWED,
    MAX_MEMBERS_ALLOWED,
    MAX_RESPONSES_ALLOWED,
    MAX_Q_PER_SURVEY,
    MAX_OPT_PER_Q
}